### ISSUE TITLE
Change README Travis Badge link

### ISSUE THREAD

**Issue by yukiisbored** [coala/coala-eclipse#33]
The travis badge link is still using `coala-analyzer` instead of `coala`.

**Comment by aashutoshrathi** [comment]
This can be a `initiatives/gci` issue.

**Comment by yukiisbored** [comment]
@aashutoshrathi This is meant not just as a GCI issue but as a general newcomer issue.

**Comment by yukiisbored** [comment]
not sure if adding initiatives/gci is important.

**Comment by xyzyg** [comment]
hi i am a beginner and i would like to work on this issue can someone give me any pointers ?

**Comment by nalinbhardwaj** [comment]
This should be closed, it was fixed in https://github.com/coala/coala-eclipse/commit/fd3b7f037ef616cb8b22c7312912ed51000567fb

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-eclipse/issues/26
